2024-02-26 14:05:51,979 - _client.py[line:1027] - INFO: HTTP Request: POST http://127.0.0.1:7861/chat/chat "HTTP/1.1 200 OK"
2024-02-26 14:05:51 | INFO | stdout | INFO:     127.0.0.1:51904 - "POST /v1/chat/completions HTTP/1.1" 200 OK
2024-02-26 14:05:52,014 - _client.py[line:1758] - INFO: HTTP Request: POST http://127.0.0.1:20000/v1/chat/completions "HTTP/1.1 200 OK"
2024-02-26 14:05:52 | INFO | httpx | HTTP Request: POST http://127.0.0.1:21001/worker_generate_stream "HTTP/1.1 200 OK"
2024-02-26 14:05:52,016 - utils.py[line:24] - ERROR: object of type 'NoneType' has no len()
Traceback (most recent call last):
  File "/mnt/workspace/Langchain-Chatchat/server/utils.py", line 22, in wrap_done
    await fn
  File "/opt/conda/envs/Langchain-Chatchat/lib/python3.10/site-packages/langchain/chains/base.py", line 381, in acall
    raise e
  File "/opt/conda/envs/Langchain-Chatchat/lib/python3.10/site-packages/langchain/chains/base.py", line 375, in acall
    await self._acall(inputs, run_manager=run_manager)
  File "/opt/conda/envs/Langchain-Chatchat/lib/python3.10/site-packages/langchain/chains/llm.py", line 275, in _acall
    response = await self.agenerate([inputs], run_manager=run_manager)
  File "/opt/conda/envs/Langchain-Chatchat/lib/python3.10/site-packages/langchain/chains/llm.py", line 142, in agenerate
    return await self.llm.agenerate_prompt(
  File "/opt/conda/envs/Langchain-Chatchat/lib/python3.10/site-packages/langchain_core/language_models/chat_models.py", line 501, in agenerate_prompt
    return await self.agenerate(
  File "/opt/conda/envs/Langchain-Chatchat/lib/python3.10/site-packages/langchain_core/language_models/chat_models.py", line 461, in agenerate
    raise exceptions[0]
  File "/opt/conda/envs/Langchain-Chatchat/lib/python3.10/site-packages/langchain_core/language_models/chat_models.py", line 564, in _agenerate_with_cache
    return await self._agenerate(
  File "/opt/conda/envs/Langchain-Chatchat/lib/python3.10/site-packages/langchain/chat_models/openai.py", line 506, in _agenerate
    return await agenerate_from_stream(stream_iter)
  File "/opt/conda/envs/Langchain-Chatchat/lib/python3.10/site-packages/langchain_core/language_models/chat_models.py", line 81, in agenerate_from_stream
    async for chunk in stream:
  File "/opt/conda/envs/Langchain-Chatchat/lib/python3.10/site-packages/langchain/chat_models/openai.py", line 477, in _astream
    if len(chunk["choices"]) == 0:
TypeError: object of type 'NoneType' has no len()
2024-02-26 14:05:52,016 - utils.py[line:27] - ERROR: TypeError: Caught exception: object of type 'NoneType' has no len()
2024-02-26 14:05:52.017 Uncaught app exception
Traceback (most recent call last):
  File "/opt/conda/envs/Langchain-Chatchat/lib/python3.10/site-packages/streamlit/runtime/scriptrunner/script_runner.py", line 534, in _run_script
    exec(code, module.__dict__)
  File "/mnt/workspace/Langchain-Chatchat/webui.py", line 64, in <module>
    pages[selected_page]["func"](api=api, is_lite=is_lite)
  File "/mnt/workspace/Langchain-Chatchat/webui_pages/dialogue/dialogue.py", line 326, in dialogue_page
    chat_box.show_feedback(**feedback_kwargs,
  File "/opt/conda/envs/Langchain-Chatchat/lib/python3.10/site-packages/streamlit_chatbox/messages.py", line 309, in show_feedback
    return streamlit_feedback(**kwargs)
  File "/opt/conda/envs/Langchain-Chatchat/lib/python3.10/site-packages/streamlit_feedback/__init__.py", line 104, in streamlit_feedback
    component_value = _component_func(
  File "/opt/conda/envs/Langchain-Chatchat/lib/python3.10/site-packages/streamlit/components/v1/components.py", line 80, in __call__
    return self.create_instance(*args, default=default, key=key, **kwargs)
  File "/opt/conda/envs/Langchain-Chatchat/lib/python3.10/site-packages/streamlit/runtime/metrics_util.py", line 396, in wrapped_func
    result = non_optional_func(*args, **kwargs)
  File "/opt/conda/envs/Langchain-Chatchat/lib/python3.10/site-packages/streamlit/components/v1/components.py", line 241, in create_instance
    return_value = marshall_component(dg, element)
  File "/opt/conda/envs/Langchain-Chatchat/lib/python3.10/site-packages/streamlit/components/v1/components.py", line 212, in marshall_component
    component_state = register_widget(
  File "/opt/conda/envs/Langchain-Chatchat/lib/python3.10/site-packages/streamlit_option_menu/streamlit_callback.py", line 20, in wrapper_register_widget
    return register_widget(*args, **kwargs)
  File "/opt/conda/envs/Langchain-Chatchat/lib/python3.10/site-packages/streamlit/runtime/state/widgets.py", line 161, in register_widget
    return register_widget_from_metadata(metadata, ctx, widget_func_name, element_type)
  File "/opt/conda/envs/Langchain-Chatchat/lib/python3.10/site-packages/streamlit/runtime/state/widgets.py", line 194, in register_widget_from_metadata
    raise DuplicateWidgetID(
streamlit.errors.DuplicateWidgetID: There are multiple widgets with the same `key=''`.

To fix this, please make sure that the `key` argument is unique for each
widget you create.
